In [2]:
import numpy as np

In [3]:
x = np.array([[1,2],[3,4]])
y = np.array([[6,7],[8,9]])
print(x)
print(y)

[[1 2]
 [3 4]]
[[6 7]
 [8 9]]


In [4]:
print(x +y)

[[ 7  9]
 [11 13]]


In [5]:
print(x-y)

[[-5 -5]
 [-5 -5]]


In [6]:
print(x*y)

[[ 6 14]
 [24 36]]


In [7]:
np.dot(x,y)

array([[22, 25],
       [50, 57]])

In [8]:
np.cross(x,y)

array([-5, -5])

In [9]:
x*y

array([[ 6, 14],
       [24, 36]])

In [2]:
a=np.array([[1,2][2,1]])
b=np.array([[3,3][2,2]])

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\Infosys Solutions\AppData\Local\Temp\ipykernel_4336\1351985941.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  x=np.array([[1,2][2,1]])
C:\Users\Infosys Solutions\AppData\Local\Temp\ipykernel_4336\1351985941.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  x=np.array([[1,2][2,1]])
C:\Users\Infosys Solutions\AppData\Local\Temp\ipykernel_4336\1351985941.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  x=np.array([[1,2][2,1

NameError: name 'np' is not defined

In [6]:
a * b

NameError: name 'a' is not defined

In [4]:
print(np.cross(a,b))
print(np.cross())

NameError: name 'a' is not defined

In [5]:
c = np.random.randint(0,100,(5,7))
print(c)

[[38 17 44 71 58 41  4]
 [34 24 67 77 18 84 84]
 [55 34  9 60 57 52  8]
 [38 63 82  1 30  0 33]
 [13 62 45 28 57 96 49]]


In [16]:
print(c.sum())
print(c.sum(axis=0)) #columns wise
print(c.sum(axis=1))# row wise

1474
[165 110 236 320 163 260 220]
[378 286 323 245 242]


In [18]:
print(c.mean())
print(c.mean(axis=0))
print(c.mean(axis=1))

42.114285714285714
[33.  22.  47.2 64.  32.6 52.  44. ]
[54.         40.85714286 46.14285714 35.         34.57142857]


similarly u can get std(),min(),max()
np numpy direct functions
np.all all value non zero

In [19]:
c.any()

True

In [22]:
np.sin(c)

array([[-0.85551998,  0.74511316,  0.74511316,  0.01770193, -0.95375265,
        -0.02655115,  0.25382336],
       [ 0.91294525,  0.74511316, -0.76825466, -0.77946607, -0.7568025 ,
         0.82682868, -0.96139749],
       [ 0.14112001,  0.84147098, -0.95375265, -0.30481062,  0.0353983 ,
        -0.42818267, -0.82181784],
       [ 0.63673801, -0.13235175, -0.99388865, -0.99975517,  0.90929743,
        -0.90557836,  0.        ],
       [-0.28790332, -0.7568025 ,  0.14987721, -0.11478481,  0.91294525,
         0.77389068,  0.01770193]])

In [23]:
np.log10(c)

C:\Users\Infosys Solutions\AppData\Local\Temp\ipykernel_2180\2814158553.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(c)


array([[1.8260748 , 1.60205999, 1.60205999, 1.64345268, 1.69019608,
        1.81954394, 1.8573325 ],
       [1.30103   , 1.60205999, 1.68124124, 1.96378783, 0.60205999,
        1.81291336, 1.23044892],
       [0.47712125, 0.        , 1.69019608, 1.77815125, 1.94448267,
        1.54406804, 1.93951925],
       [1.77085201, 1.39794001, 1.90308999, 1.74036269, 0.30103   ,
        1.38021124,       -inf],
       [1.20411998, 0.60205999, 1.2787536 , 1.83884909, 1.30103   ,
        1.84509804, 1.64345268]])

boolean filter


In [27]:
x = np.random.randint(0,100,(8,15))
print(x)

[[21 61 40 43 83 31 42 94 71 25 52  7 93 33 33]
 [57 77 82 49 55 95 82 95 12 18  0 75  2 38 89]
 [90 75  2 69 87  3 50 69  0 25 23 94 58 36 22]
 [99 74 13 98 21 20 91 20 94 86 82 23 86 65 12]
 [45 25 90 23  8 75 27 60 54 53 45 66 78 82 27]
 [63 11 80 63 10 65 78 99  5 79 58  2 93 50 27]
 [97 50 15 39 95 47 90 16 13 29 59 55  7  7 26]
 [ 7 14 45 35 88 22 39 68 96 51 21 51  7 27  5]]


In [28]:
x > 50 #just display the boolean matrix

array([[False,  True, False, False,  True, False, False,  True,  True,
        False,  True, False,  True, False, False],
       [ True,  True,  True, False,  True,  True,  True,  True, False,
        False, False,  True, False, False,  True],
       [ True,  True, False,  True,  True, False, False,  True, False,
        False, False,  True,  True, False, False],
       [ True,  True, False,  True, False, False,  True, False,  True,
         True,  True, False,  True,  True, False],
       [False, False,  True, False, False,  True, False,  True,  True,
         True, False,  True,  True,  True, False],
       [ True, False,  True,  True, False,  True,  True,  True, False,
         True,  True, False,  True, False, False],
       [ True, False, False, False,  True, False,  True, False, False,
        False,  True,  True, False, False, False],
       [False, False, False, False,  True, False, False,  True,  True,
         True, False,  True, False, False, False]])

In [31]:
x[x>50]

array([61, 83, 94, 71, 52, 93, 57, 77, 82, 55, 95, 82, 95, 75, 89, 90, 75,
       69, 87, 69, 94, 58, 99, 74, 98, 91, 94, 86, 82, 86, 65, 90, 75, 60,
       54, 53, 66, 78, 82, 63, 80, 63, 65, 78, 99, 79, 58, 93, 97, 95, 90,
       59, 55, 88, 68, 96, 51, 51])

In [32]:
x[x<20]

array([ 7, 12, 18,  0,  2,  2,  3,  0, 13, 12,  8, 11, 10,  5,  2, 15, 16,
       13,  7,  7,  7, 14,  7,  5])

In [34]:
f1 = x > 20
f2 = x < 50
x[f1 & f2]

array([21, 40, 43, 31, 42, 25, 33, 33, 49, 38, 25, 23, 36, 22, 21, 23, 45,
       25, 23, 27, 45, 27, 27, 39, 47, 29, 26, 45, 35, 22, 39, 21, 27])

Numpy provide efficent storage it also provide better ways of handling fo preprocessing it is fast it is easy to learn NumPy uses relatively less memory to store data.

In [8]:
import numpy as np
myarr = np.array([[3,6,37,7]], np.int64)
myarr[0,1]

6

In [9]:
myarr.shape

(1, 4)

In [10]:
myarr.dtype

dtype('int64')

In [11]:
myarr[0,1] = 45
myarr

array([[ 3, 45, 37,  7]], dtype=int64)

# Array creation: conversion from other python structures

In [12]:
listarray = np.array([[1,2,3], [5,8,5],[0,3,1]])
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [13]:
listarray.dtype

dtype('int32')

In [14]:
listarray.shape

(3, 3)

In [15]:
listarray.size

9

In [16]:
np.array({34,23,23}) #using dictionary

array({34, 23}, dtype=object)

In [7]:
zeros = np.zeros({2,5})
zeros

NameError: name 'np' is not defined

In [23]:
rng = np.arange(21)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [25]:
lspace = np.linspace(1,5,4)
lspace


array([1.        , 2.33333333, 3.66666667, 5.        ])

In [12]:
emp = np.empty(4,6)
emp

TypeError: Cannot interpret '6' as a data type

In [28]:
emp_like = np.empty_like(lspace)
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [29]:
ide = np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [30]:
ide.shape

(45, 45)

In [31]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [35]:
arr = arr.reshape(3,33)

In [37]:
arr = arr.ravel()
arr.shape


(99,)

In [10]:
x =[[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)

In [41]:
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [42]:
ar.sum(axis=0)

array([12,  8,  9])

In [43]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [44]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [45]:
ar.flat

In [46]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [47]:
ar.ndim


2

In [48]:
ar.size

9

In [49]:
ar.nbytes

36

In [51]:
one = np.array([1,3,4,634,2])
one.argmax()

3

In [52]:
one.argmin()

0

In [53]:
one.argsort()


array([0, 4, 1, 2, 3], dtype=int64)

In [54]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [55]:
ar.argmin()

8

In [56]:
ar.argmax()

6

In [57]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [59]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [60]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [61]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [62]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [63]:
ar2 = np.array([[1,2,1],
[8,5,12],
[15,2,0]])

In [66]:
ar + ar2

array([[ 2,  4,  2],
       [16, 10, 24],
       [30,  4,  0]])

In [67]:
ar * ar2

array([[  1,   4,   1],
       [ 64,  25, 144],
       [225,   4,   0]])

In [68]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.        ],
       [2.82842712, 2.23606798, 3.46410162],
       [3.87298335, 1.41421356, 0.        ]])

In [69]:
ar.sum()

46

In [70]:
ar

array([[ 1,  2,  1],
       [ 8,  5, 12],
       [15,  2,  0]])

In [71]:
np.where(ar>5)

(array([1, 1, 2], dtype=int64), array([0, 2, 0], dtype=int64))

In [72]:
np.count_nonzero(ar)

8

In [75]:
ar[1,2] = 0

In [73]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [80]:
import numpy as np
py_ar = [0,4,55,2]
np_ar = np.array(py_ar)
sys.getsizeof(1) * len(py_ar)

112

In [81]:
np_ar.itemsize * np_ar.size

16

In [82]:
np_ar.tolist()

[0, 4, 55, 2]

numpy array with a series 
numpy array with random number
ndarray.size this is equal to the product elements in numpy array.
ndarray,itemsize 
numpy properties --
ndim, nsize,np.shape,np.arange

In [15]:
np.linspace(0, 5/3, 6)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667])

indexing one dimensional numpy arrays

In [7]:
a = np.array([1, 2, 3, 4, 5, 6])
a[1]

2